export const BigQuery = [
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "2427",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0", // interactions
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0", // interactions
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "2513",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933", // views
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary", // title
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "1320",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "1289",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "988",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "967",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "864",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "850",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "770",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "756",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "712",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "704",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "666",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "666",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "646",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "639",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "610",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "610",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "574",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "579",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "557",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "561",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "536",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "545",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "512",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "520",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "488",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "495",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "480",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "487",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "467",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "475",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "454",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "462",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "441",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "451",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "434",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "443",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "424",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "432",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "415",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "415",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "410",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "417",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  },
  {
    "total_count": "905",
    "status_code": "200",
    "results_data_metrics_player_loads": "0",
    "results_data_metrics_urls_copied": "0",
    "results_data_metrics_percentage_watched": "410",
    "results_data_metrics_displays": "7175",
    "results_data_metrics_embeds_copied": "0",
    "results_data_metrics_time_watched": "618900533",
    "results_data_metrics_uniq_video_starts": "2180",
    "results_data_metrics_video_starts": "2685",
    "results_data_metrics_emails_sent": "0",
    "results_data_metrics_discovery_leads": "2940",
    "results_data_metrics_digg": "0",
    "results_data_metrics_autoplays": "0",
    "results_data_metrics_plays_requested": "3487",
    "results_data_metrics_playthrough_100": "371",
    "results_data_metrics_playthrough_25": "613",
    "results_data_metrics_playthrough_50": "448",
    "results_data_metrics_playthrough_75": "401",
    "results_data_metrics_facebook": "0",
    "results_data_metrics_segment_watched": "417",
    "results_data_metrics_discovery_plays": "35213",
    "results_data_metrics_replays": "0",
    "results_data_metrics_twitter": "0",
    "results_data_metrics_uniq_displays": "6299",
    "results_data_metrics_uniq_plays_requested": "2933",
    "results_data_group_status": "live",
    "results_data_group_name": "Guns & Empathy: A Documentary",
    "results_data_group_type": "video",
    "results_data_group_is_live_stream": "false",
    "results_data_group_asset": "MxczBqODE6lruC7rBHsNNYQzMgi0DXNp",
    "results_end_date": "2017-02-27 00:00:00 UTC",
    "results_start_date": "2017-02-27 00:00:00 UTC",
    "status": "OK",
    "result_count": "905"
  }
]
